/*
 * NXP S32K388/S32K389 Quad Serial Peripheral Interface (QuadSPI) Emulation
 *
 * See s32k3_qspi.h for the manual cross-reference (S32K3xx Reference
 * Manual Rev. 11, Chapter 80) and the list of modeling simplifications.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#include "qemu/osdep.h"
#include "hw/core/sysbus.h"
#include "hw/core/qdev-properties.h"
#include "hw/core/irq.h"
#include "qapi/error.h"
#include "qemu/log.h"
#include "qemu/module.h"
#include "qom/object.h"
#include "s32k3_qspi.h"

static void s32k3_qspi_update_irq(S32K3QspiState *s)
{
    /* RSER bit N enables the corresponding FR bit as an interrupt source
     * (manual 80.13.2.27) - only TFF (bit 0) is meaningfully generated by
     * this model. */
    bool level = (s->rser & S32K3_QSPI_FR_TFF) && (s->fr & S32K3_QSPI_FR_TFF);

    qemu_set_irq(s->irq, level);
}

/* Walk one LUT sequence (5 registers = 10 instructions starting at
 * lut[seqid * 5]) looking for a READ or WRITE opcode - see the header's
 * scope note re: why this model only cares about those two. */
static void s32k3_qspi_exec_seq(S32K3QspiState *s, uint32_t seqid,
                                  uint32_t idatsz)
{
    uint32_t base = seqid * S32K3_QSPI_LUT_SEQ_REGS;
    S32K3QspiLutOp op = S32K3_QSPI_LUT_OP_STOP;

    if (base + S32K3_QSPI_LUT_SEQ_REGS > S32K3_QSPI_NUM_LUT) {
        qemu_log_mask(LOG_GUEST_ERROR,
                      "s32k3_qspi: SEQID %u out of range\n", seqid);
        return;
    }

    for (uint32_t i = 0; i < S32K3_QSPI_LUT_SEQ_REGS; i++) {
        uint32_t word = s->lut[base + i];
        uint32_t instr0 = (word >> 10) & 0x3F;
        uint32_t instr1 = (word >> 26) & 0x3F;

        if (instr0 == S32K3_QSPI_LUT_OP_STOP &&
            instr1 == S32K3_QSPI_LUT_OP_STOP) {
            break;
        }
        if (instr0 == S32K3_QSPI_LUT_OP_READ ||
            instr1 == S32K3_QSPI_LUT_OP_READ) {
            op = S32K3_QSPI_LUT_OP_READ;
            break;
        }
        if (instr0 == S32K3_QSPI_LUT_OP_WRITE ||
            instr1 == S32K3_QSPI_LUT_OP_WRITE) {
            op = S32K3_QSPI_LUT_OP_WRITE;
            break;
        }
    }

    if (idatsz == 0 || s->sfar + idatsz > S32K3_QSPI_FLASH_SIZE) {
        if (idatsz != 0) {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "s32k3_qspi: SFAR 0x%x + IDATSZ %u exceeds the "
                          "%u-byte emulated flash\n", s->sfar, idatsz,
                          S32K3_QSPI_FLASH_SIZE);
        }
        op = S32K3_QSPI_LUT_OP_STOP; /* command-only (e.g. write-enable) */
    }

    switch (op) {
    case S32K3_QSPI_LUT_OP_READ: {
        uint32_t n = idatsz / 4;

        if (n > S32K3_QSPI_NUM_RBDR) {
            n = S32K3_QSPI_NUM_RBDR;
        }
        for (uint32_t i = 0; i < n; i++) {
            memcpy(&s->rbdr[i], &s->flash[s->sfar + i * 4], 4);
        }
        s->rbdr_count = n;
        break;
    }
    case S32K3_QSPI_LUT_OP_WRITE: {
        uint32_t n = idatsz / 4;

        if (n > s->tx_count) {
            n = s->tx_count;
        }
        for (uint32_t i = 0; i < n; i++) {
            memcpy(&s->flash[s->sfar + i * 4], &s->tx_fifo[i], 4);
        }
        s->tx_count = 0;
        break;
    }
    default:
        break; /* command-only sequence (write-enable, read-status, ...) */
    }

    s->fr |= S32K3_QSPI_FR_TFF;
    s32k3_qspi_update_irq(s);
}

static uint64_t s32k3_qspi_read(void *opaque, hwaddr addr, unsigned size)
{
    S32K3QspiState *s = opaque;

    if (addr >= S32K3_QSPI_REGS_MEM_SIZE) {
        qemu_log_mask(LOG_GUEST_ERROR,
                      "s32k3_qspi: read from invalid offset 0x%"
                      HWADDR_PRIx "\n", addr);
        return 0;
    }

    switch (addr) {
    case S32K3_QSPI_MCR:
        return s->mcr;
    case S32K3_QSPI_IPCR:
        return s->ipcr;
    case S32K3_QSPI_SFAR:
        return s->sfar;
    case S32K3_QSPI_RBSR:
        return s->rbdr_count << 8; /* RDBFL field, manual 80.13.2.18 */
    case S32K3_QSPI_TBSR:
        return s->tx_count << 16; /* TXBFL field, manual 80.13.2.22 */
    case S32K3_QSPI_TBDR:
        return 0; /* write-only in practice */
    case S32K3_QSPI_SR:
        return s->sr;
    case S32K3_QSPI_FR:
        return s->fr;
    case S32K3_QSPI_RSER:
        return s->rser;
    case S32K3_QSPI_LUTKEY:
        return 0; /* write-only key, always reads 0 */
    case S32K3_QSPI_LCKCR:
        return s->lckcr;
    default:
        break;
    }

    for (int i = 0; i < S32K3_QSPI_NUM_RBDR; i++) {
        if (addr == S32K3_QSPI_RBDR(i)) {
            return s->rbdr[i];
        }
    }
    for (int i = 0; i < S32K3_QSPI_NUM_LUT; i++) {
        if (addr == S32K3_QSPI_LUT(i)) {
            return s->lut[i];
        }
    }

    return 0;
}

static void s32k3_qspi_write(void *opaque, hwaddr addr, uint64_t val64,
                               unsigned size)
{
    S32K3QspiState *s = opaque;
    uint32_t val = val64;

    if (addr >= S32K3_QSPI_REGS_MEM_SIZE) {
        qemu_log_mask(LOG_GUEST_ERROR,
                      "s32k3_qspi: write to invalid offset 0x%"
                      HWADDR_PRIx " (value 0x%" PRIx32 ")\n", addr, val);
        return;
    }

    switch (addr) {
    case S32K3_QSPI_MCR:
        if (val & S32K3_QSPI_MCR_CLR_RXF) {
            s->rbdr_count = 0;
            memset(s->rbdr, 0, sizeof(s->rbdr));
        }
        if (val & S32K3_QSPI_MCR_CLR_TXF) {
            s->tx_count = 0;
        }
        s->mcr = val & ~(S32K3_QSPI_MCR_CLR_RXF | S32K3_QSPI_MCR_CLR_TXF);
        return;
    case S32K3_QSPI_IPCR: {
        uint32_t seqid = (val & S32K3_QSPI_IPCR_SEQID_MASK) >>
                         S32K3_QSPI_IPCR_SEQID_SHIFT;
        uint32_t idatsz = val & S32K3_QSPI_IPCR_IDATSZ_MASK;

        s->ipcr = val;
        if (s->mcr & S32K3_QSPI_MCR_MDIS) {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "s32k3_qspi: IPCR written while MDIS=1\n");
            return;
        }
        s->sr |= S32K3_QSPI_SR_IP_ACC;
        s32k3_qspi_exec_seq(s, seqid, idatsz);
        s->sr &= ~S32K3_QSPI_SR_IP_ACC;
        return;
    }
    case S32K3_QSPI_SFAR:
        s->sfar = val;
        return;
    case S32K3_QSPI_TBDR:
        if (s->tx_count < S32K3_QSPI_NUM_RBDR) {
            s->tx_fifo[s->tx_count++] = val;
        } else {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "s32k3_qspi: TBDR write with TX FIFO full\n");
        }
        return;
    case S32K3_QSPI_SR:
        qemu_log_mask(LOG_GUEST_ERROR, "s32k3_qspi: SR is read-only\n");
        return;
    case S32K3_QSPI_FR:
        s->fr &= ~(val & S32K3_QSPI_FR_W1C_MASK);
        s32k3_qspi_update_irq(s);
        return;
    case S32K3_QSPI_RSER:
        s->rser = val;
        s32k3_qspi_update_irq(s);
        return;
    case S32K3_QSPI_LUTKEY:
        s->locked = (val != S32K3_QSPI_LUTKEY_VALUE) ? s->locked : false;
        return;
    case S32K3_QSPI_LCKCR:
        if (val & S32K3_QSPI_LCKCR_LOCK) {
            s->locked = true;
        }
        if (val & S32K3_QSPI_LCKCR_UNLOCK) {
            /* Real hardware also requires LUTKEY to have just been
             * written correctly; s->locked was already cleared by that
             * write above, so this is effectively a no-op re-confirm. */
        }
        s->lckcr = val & (S32K3_QSPI_LCKCR_LOCK | S32K3_QSPI_LCKCR_UNLOCK);
        return;
    default:
        break;
    }

    for (int i = 0; i < S32K3_QSPI_NUM_LUT; i++) {
        if (addr == S32K3_QSPI_LUT(i)) {
            if (s->locked) {
                qemu_log_mask(LOG_GUEST_ERROR,
                              "s32k3_qspi: LUT%d write while locked "
                              "(LUTKEY/LCKCR unlock sequence required), "
                              "ignored\n", i);
                return;
            }
            s->lut[i] = val;
            return;
        }
    }

    qemu_log_mask(LOG_GUEST_ERROR,
                  "s32k3_qspi: write to invalid offset 0x%" HWADDR_PRIx
                  " (value 0x%" PRIx32 ")\n", addr, val);
}

static const MemoryRegionOps s32k3_qspi_ops = {
    .read = s32k3_qspi_read,
    .write = s32k3_qspi_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .impl = { .min_access_size = 4, .max_access_size = 4 },
    .valid = { .min_access_size = 4, .max_access_size = 4 },
};

static uint64_t s32k3_qspi_ardb_read(void *opaque, hwaddr addr, unsigned size)
{
    S32K3QspiState *s = opaque;
    uint32_t idx = addr / 4;

    if (idx >= S32K3_QSPI_NUM_RBDR) {
        return 0;
    }
    return s->rbdr[idx];
}

static void s32k3_qspi_ardb_write(void *opaque, hwaddr addr, uint64_t val,
                                    unsigned size)
{
    qemu_log_mask(LOG_GUEST_ERROR, "s32k3_qspi: ARDB is read-only\n");
}

static const MemoryRegionOps s32k3_qspi_ardb_ops = {
    .read = s32k3_qspi_ardb_read,
    .write = s32k3_qspi_ardb_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .impl = { .min_access_size = 4, .max_access_size = 4 },
    .valid = { .min_access_size = 4, .max_access_size = 4 },
};

static void s32k3_qspi_reset(DeviceState *dev)
{
    S32K3QspiState *s = S32K3_QSPI(dev);

    s->mcr = S32K3_QSPI_MCR_RESET;
    s->ipcr = 0;
    s->sfar = 0;
    s->sr = S32K3_QSPI_SR_RESET;
    s->fr = S32K3_QSPI_FR_RESET;
    s->rser = 0;
    s->lckcr = S32K3_QSPI_LCKCR_LOCK;
    s->locked = true;
    s->rbdr_count = 0;
    s->tx_count = 0;
    memset(s->rbdr, 0, sizeof(s->rbdr));
    memset(s->tx_fifo, 0, sizeof(s->tx_fifo));
    memset(s->lut, 0, sizeof(s->lut));
    memset(s->flash, 0xFF, S32K3_QSPI_FLASH_SIZE); /* erased NOR flash */
    s32k3_qspi_update_irq(s);
}

static void s32k3_qspi_instance_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32K3QspiState *s = S32K3_QSPI(obj);

    memory_region_init_io(&s->iomem, obj, &s32k3_qspi_ops, s,
                          TYPE_S32K3_QSPI, S32K3_QSPI_REGS_MEM_SIZE);
    sysbus_init_mmio(sbd, &s->iomem);

    memory_region_init_io(&s->ardb_iomem, obj, &s32k3_qspi_ardb_ops, s,
                          TYPE_S32K3_QSPI ".ardb", S32K3_QSPI_ARDB_MEM_SIZE);
    sysbus_init_mmio(sbd, &s->ardb_iomem);

    sysbus_init_irq(sbd, &s->irq);

    s->flash = g_malloc(S32K3_QSPI_FLASH_SIZE);
}

static void s32k3_qspi_realize(DeviceState *dev, Error **errp)
{
    s32k3_qspi_reset(dev);
}

static void s32k3_qspi_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->realize = s32k3_qspi_realize;
}

static const TypeInfo s32k3_qspi_info = {
    .name = TYPE_S32K3_QSPI,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(S32K3QspiState),
    .instance_init = s32k3_qspi_instance_init,
    .class_init = s32k3_qspi_class_init,
};

static void s32k3_qspi_register_types(void)
{
    type_register_static(&s32k3_qspi_info);
}

type_init(s32k3_qspi_register_types)
